kind: pipeline
type: docker
name: backend-build

steps:
  - name: build-backend
    image: docker:19.03
    environment:
      QUARKUS_PROFILE: prod
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - apk add --no-cache maven openjdk17  
      - cd Hotel/backend/sistema-hoteles-be
      - mvn clean install
      - docker build -t mi-backend-quarkus .

  - name: sonar-scan-backend
    image: sonarsource/sonar-scanner-cli
    environment:
      SONAR_HOST_URL: https://fifty-pumas-mix.loca.lt
      SONAR_LOGIN:
        from_secret: squ_fee0b0c3a7a7792eabc285aecbf3dd0b7b6641be
    commands:
      - cd Hotel/backend/sistema-hoteles-be
      - sonar-scanner -Dsonar.projectKey=backend -Dsonar.sources=./ -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_LOGIN

  - name: publish-backend
    image: plugins/docker
    settings:
      repo: sebas234/mi-backend-quarkus
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

trigger:
  event:
    - push
    - pull_request
    - custom

---

kind: pipeline
type: docker
name: frontend-build

steps:
  - name: build-frontend
    image: docker:19.03
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      CI: false
    commands:
      - apk add --no-cache nodejs npm  
      - cd Hotel/frontend/sistema_hoteles
      - npm install --no-audit
      - npm run build
      - docker build -t mi-frontend-react .

  - name: sonar-scan-frontend
    image: sonarsource/sonar-scanner-cli
    environment:
      SONAR_HOST_URL: https://fifty-pumas-mix.loca.lt
      SONAR_LOGIN:
        from_secret: squ_fee0b0c3a7a7792eabc285aecbf3dd0b7b6641be
    commands:
      - cd Hotel/frontend/sistema_hoteles
      - sonar-scanner -Dsonar.projectKey=frontend -Dsonar.sources=./ -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_LOGIN

  - name: publish-frontend
    image: plugins/docker
    settings:
      repo: sebas234/mi-frontend-react
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

trigger:
  event:
    - push
    - pull_request
    - custom

