kind: pipeline
type: docker
name: test-pipeline

steps:
  - name: test-step
    image: alpine
    commands:
      - echo "Pipeline is working!"

trigger:
  branch:
    - main
  event:
    - push
    - pull_request


