kind: pipeline
type: docker
name: backend-build

steps:
  - name: verify-docker
    image: busybox
    commands:
      - if ! command -v docker &> /dev/null; then echo "Docker is not installed"; exit 1; fi
      - echo "Docker is installed and accessible."

  - name: build-backend
    image: maven:3.8.4-openjdk-17
    environment:
      QUARKUS_PROFILE: prod
    commands:
      - cd Hotel/backend/sistema-hoteles-be
      - mvn clean install
      - if [ $? -ne 0 ]; then echo "Maven build failed"; exit 1; fi

  - name: sonar-scan-backend
    image: sonarsource/sonar-scanner-cli
    environment:
      SONAR_HOST_URL: "https://fifty-pumas-mix.loca.lt"
      SONAR_LOGIN:
        from_secret: "squ_ae9f1f58e44e14493e5034742377319713dcd4d1"
    commands:
      - cd Hotel/backend/sistema-hoteles-be
      - sonar-scanner -X -Dsonar.projectKey=backend -Dsonar.sources=./ -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_LOGIN
      - if [ $? -ne 0 ]; then echo "SonarQube scan failed"; exit 1; fi

  - name: publish-backend
    image: plugins/docker
    settings:
      repo: sebas234/mi-backend-quarkus
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Hotel/backend/sistema-hoteles-be/Dockerfile
      context: Hotel/backend/sistema-hoteles-be
    commands:
      - echo "Publishing backend Docker image"
      - docker build -t mi-backend-quarkus .
      - if [ $? -ne 0 ]; then echo "Docker build failed"; exit 1; fi

trigger:
  event:
    - push
    - pull_request
    - custom

---

kind: pipeline
type: docker
name: frontend-build

steps:
  - name: verify-docker
    image: busybox
    commands:
      - if ! command -v docker &> /dev/null; then echo "Docker is not installed"; exit 1; fi
      - echo "Docker is installed and accessible."

  - name: build-frontend
    image: node:14-alpine
    environment:
      CI: false
    commands:
      - cd Hotel/frontend/sistema_hoteles
      - npm install --no-audit
      - if [ $? -ne 0 ]; then echo "npm install failed"; exit 1; fi
      - npm run build
      - if [ $? -ne 0 ]; then echo "npm build failed"; exit 1; fi

  - name: sonar-scan-frontend
    image: sonarsource/sonar-scanner-cli
    environment:
      SONAR_HOST_URL: "https://fifty-pumas-mix.loca.lt"
      SONAR_LOGIN:
        from_secret: "squ_ae9f1f58e44e14493e5034742377319713dcd4d1"
    commands:
      - cd Hotel/frontend/sistema_hoteles
      - sonar-scanner -X -Dsonar.projectKey=frontend -Dsonar.sources=./ -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_LOGIN
      - if [ $? -ne 0 ]; then echo "SonarQube scan failed"; exit 1; fi

  - name: publish-frontend
    image: plugins/docker
    settings:
      repo: sebas234/mi-frontend-react
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Hotel/frontend/sistema_hoteles/Dockerfile
      context: Hotel/frontend/sistema_hoteles
    commands:
      - echo "Publishing frontend Docker image"
      - docker build -t mi-frontend-react .
      - if [ $? -ne 0 ]; then echo "Docker build failed"; exit 1; fi

trigger:
  event:
    - push
    - pull_request
    - custom

