kind: pipeline
type: docker
name: backend-build

steps:
  - name: build-backend
    image: maven:3.8.4-openjdk-17
    environment:
      QUARKUS_PROFILE: prod
    commands:
      - cd Hotel/backend/sistema-hoteles-be
      - mvn clean install
  
  - name: clean-sonar-cache
    image: alpine
    commands:
      - rm -rf /opt/sonar-scanner/.sonar/_tmp

  - name: sonar-scan-backend
    image: sonarsource/sonar-scanner-cli
    user: root
    environment:
      SONAR_SCANNER_OPTS: "-Xmx4g"
      SONAR_HOST_URL: "https://icy-tires-tie.loca.lt/"
      SONAR_LOGIN:
        from_secret: sonar_login
    commands:
      - cd Hotel/backend/sistema-hoteles-be
      - sonar-scanner -X -Dsonar.projectKey=backend -Dsonar.sources=./ -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.scanner.socketTimeout=300000 -Dsonar.java.binaries=target/classes -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml -Dsonar.verbose=true -Dsonar.scanner.forceHTTP1=true

    depends_on:
      - build-backend

  - name: publish-backend
    image: plugins/docker
    settings:
      repo: sebas234/mi-backend-quarkus
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Hotel/backend/sistema-hoteles-be/Dockerfile
      context: Hotel/backend/sistema-hoteles-be
    depends_on:
      - sonar-scan-backend

  - name: notify-email
    image: drillster/drone-email
    settings:
      host: smtp.gmail.com   
      username: emailjsReyes@gmail.com     
      password: rqsn hmgf niuo vjut        
      from: emailjsReyes@gmail.com 
      recipients:
        - jpestrada@unis.edu.gt
        - juanpablo08082002@hotmail.com
      subject: "Drone Build Notification"
    when:
      status:
        - failure
    depends_on:
      - build-backend
      - sonar-scan-backend
      - publish-backend
    failure: true

trigger:
  event:
    - push
    - pull_request
    - custom

secrets:
  - sonar_login
  - docker_username
  - docker_password

---

kind: pipeline
type: docker
name: frontend-build

steps:
  - name: build-frontend
    image: node:14-alpine
    environment:
      CI: false
    commands:
      - cd Hotel/frontend/sistema_hoteles
      - npm install --no-audit
      - npm run build

  - name: publish-frontend
    image: plugins/docker
    settings:
      repo: sebas234/mi-frontend-react
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Hotel/frontend/sistema_hoteles/Dockerfile
      context: Hotel/frontend/sistema_hoteles
    depends_on:
      - build-frontend

trigger:
  event:
    - push
    - pull_request
    - custom

secrets:
  - docker_username
  - docker_password

  
