version: '3.8'

services:
  backend:
    build: ./backend/sistema-hoteles-be
    ports:
      - "8081:8081"
    networks:
      - hotel-network

  frontend:
    build: ./frontend/sistema_hoteles
    ports:
      - "3000:80"
    networks:
      - hotel-network

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - hotel-network
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4G

  db:
    image: postgres:latest
    container_name: sonar-db
    networks:
      - hotel-network
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - ./sonar-postgres-data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - hotel-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=yourpassword
    networks:
      - hotel-network

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      - hotel-network
    environment:
      - INFLUXDB_DB=metrics
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword
    volumes:
      - influxdb-storage:/var/lib/influxdb

  chronograf:
    image: chronograf:latest
    container_name: chronograf
    ports:
      - "8888:8888"
    networks:
      - hotel-network
    environment:
      - INFLUXDB_URL=http://influxdb:8086
    depends_on:
      - influxdb

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - hotel-network
    depends_on:
      - influxdb

networks:
  hotel-network:
    driver: bridge

volumes:
  influxdb-storage:


