version: '3.8'

services:
  backend:
    build: ./backend/sistema-hoteles-be
    ports:
      - "8081:8081"
    networks:
      - hotel-network

  frontend:
    build: ./frontend/sistema_hoteles
    ports:
      - "3000:80"
    networks:
      - hotel-network

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - hotel-network
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar

  db:
    image: postgres:latest
    container_name: sonar-db
    networks:
      - hotel-network
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar

networks:
  hotel-network:
    driver: bridge
