name: SonarQube analysis

on:
  push:
    branches: [ "main", "dev", "uat" ]
  pull_request:
    branches: [ "main", "dev", "uat" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # Adoptium's Temurin is a popular JDK distribution
        java-version: '17'


    - name: Cache SonarQube packages
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven

    - name: Build and analyze with SonarQube
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Este es el token que proporciona GitHub automáticamente
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Este es el token que configuraste para SonarQube
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} # Este es el URL de tu instancia de SonarQube
      run: |
        mvn -f Hotel/backend/sistema-hoteles-be/pom.xml clean verify -DskipTests sonar:sonar \
          -Dsonar.projectKey=Sebasreyes25_PROYECTO-ARQ_AZGbWDf3MTMJDWtiM_pe \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN
